# -*- coding: utf-8 -*-
"""M5-Assignment Level-2-SMOTE(Data Imbalance).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_XMJDQVRnPCUwckU8hJl_5SPPj40N2I
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('/content/drive/MyDrive/creditcard.csv')

df

df.shape

df['Class']=pd.to_numeric(df['Class'],errors='coerce')

df.dropna(subset=['Class'])

target=df.values[:,-1]

target

from collections import Counter

counter=Counter(target)

for k,v in counter.items():
  per=v/len(target)*100
  print('Class=%d,Count=%d,Percentage=%.3f%%'%(k,v,per))

ax=df.hist(bins=100)

for axis in ax.flatten():
  axis.set_xticklabels([])
  axis.set_yticklabels([])

plt.show()

X=df.drop(['Class'],axis=1)
y=df.Class

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

from imblearn.over_sampling import SMOTE

counter=Counter(y_train)
print(' Before',counter)
smt=SMOTE()

X_train_sm,y_train_sm=smt.fit_resample(x_train,y_train)

counter=Counter(y_train_sm)
print('After',counter)